name: Continuous Integration
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:  
  test-sbt:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11, macos-12]
        website: ['oracle.com', 'jdk.java.net']
      fail-fast: false
    name: Test sbt on ${{ matrix.os }} - ${{ matrix.website }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: oracle-actions/setup-java@v1.1.2
      with:
        website: ${{ matrix.website }}
    - run: java -version
    - run: sbt scripted
